spring:

  application:
    name: FoodSommelier

  config:
    import: optional:.env[.properties]

  datasource:
    # mySql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

google:
  client:
    client-id: ${Google_Client_Id}